project:
  type: website
  output-dir: docs

website:

  twitter-card: true
  site-url: https://github.com/patrickzerrer/R_Hands_on_Book
  open-graph: true
  
  navbar: 
    title: false
    logo: Bilder/logo_ub_2021.png

    background: "#e3dac9"
    foreground: "secondary"
    search: true
    left: 
      - text: "Home"
        file: Home.qmd
      - text: "Der Kurs"
        file: Skript_1.1.qmd
      - text: "Die Grundidee"
        file: Hintergrund.qmd
      - text: "Die Autor:innen"
        file: Autoren.qmd
    
    right: 
      - icon: github
        href: https://github.com/patrickzerrer/R_Hands_on_Book
      
  sidebar: 
    style: "docked"
    background: "light"
    foreground: "secondary"
    contents:
    - section: "Data-Bootcamp: Einführung in R"
      contents:
      - Skript_1.1.qmd
      - Skript_1.3.qmd
      - Skript_1.4.qmd

    - section: "Data-Bootcamp: Datensätze"
      contents:
      - Skript_2.1.qmd
      - Skript_2.2.qmd
      - Skript_2.3.qmd

    - section: "Data-Bootcamp: Der Umgang mit Daten"
      contents:
      - Skript_3.1.qmd
      - Skript_3.2.qmd
      - Skript_3.3.qmd
      - Skript_3.4.qmd

    - section: "Die ersten Schritte bei der Datenanalyse"
      contents:
      - Skript_4.1.qmd
      - Skript_4.2.qmd
      - Skript_4.3.qmd
      - Skript_4.4.qmd

    - section: "Von einzelnen Antworten zum Index"
      contents:
      - Skript_5.1.qmd
      - Skript_5.2.qmd
      - Skript_5.3.qmd    

    - section: "Das Überprüfen von Unterschieden"
      contents:
      - Skript_6.1.qmd
      - Skript_6.2.qmd
      - Skript_6.3.qmd
      - Skript_6.4.qmd

    - section: "Das Überprüfen von Zusammenhängen"
      contents:
      - Skript_7.1.qmd
      - Skript_7.2.qmd
      - Skript_7.3.qmd
      - Skript_7.4.qmd
  
<<<<<<< HEAD
  page-footer: "Copyright 2023, Design by Katharina Maubach & Patrick Zerrer"

=======
  page-footer: 
    left: "Copyright 2023, Design by Katharina Maubach & Patrick Zerrer"
    right: "![](Bilder/Logo_Stiftung_Hochschullehre_pos.jpg){width=120} ![](Bilder/Skill_UB_Icons_1_quer__blau.jpeg){width=120} "
    
>>>>>>> 310757c20b6e67efcb3cca68a7dc8427760383bc
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    
editor: visual

